### ISSUE TITLE
Incorrect spacing and pagination

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#27]
Tokens should be positioned with the same alignment on all pages, so that they can be cut with a machine.  This is not the case in the attached file.
- [x] Some tokens cross a page boundary (see pp. 4-5)
- [x] Some tokens are longer than others (see pp. 1, 2, 3).

See [qr.pdf](https://github.com/dnna/pixelbonus/files/144566/qr.pdf)

**Comment by dnna** [comment]
This should be fixed now. Turns out there were a number of issues causing it:
1. The QR library did not generate fixed size images but they could vary slightly depending on the code.
2. The specific monospace font used was supported by wkhtmltopdf on our Windows PCs but not in Okeanos' Linux.
3. Page breaks within tables seem to be handled incorrectly by wkhtmltopdf.
