### ISSUE TITLE
Successive applications of puppet apply should no do anything

### ISSUE THREAD

**Issue by dspinellis** [dnna/pixelbonus#3]
Instead, they currently re-run a number of rule:

```
Notice: /Stage[main]/Main/Exec[apt-update]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[allow-override]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[enable-mod-rewrite]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[enable-mcrypt]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[composer-update]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[setup-document-root]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[fix-permissions]/returns: executed successfully
Notice: /Stage[main]/Main/Exec[schema-update]/returns: executed successfully
```

This can probably be addressed by using appropriate `creates` or `refreshonly` and `notify` entries.

**Comment by dnna** [comment]
I have refactored pixelbonus.pp and added several conditions to prevent re-execution of finished commands. Unfortunately I have noticed the undesirable side-effect that if **Exec['composer-update']** fails but **Vcsrepo['/var/www/pixelbonus']** finishes successfully then application will be stuck into a non-working state. This happens because subsequent puppet runs will not re-execute vcsrepo (the repo was cloned successfully so vcsrepo is done) and composer-update expects this in order to run.

The desired flow here is that if vcsrepo runs (which means it has detected a new version in the repo), then composer-update should run. It should also run, however, if it failed to in the previous puppet apply to prevent the application from being stuck into the non-working state.

I'm leaving the issue open until we can find a way to solve this correctly.
